name: Bug Report
description: File a bug report or unexpected behavior.
body:
  - type: markdown
    attributes:
      value: |
        Before reporting a bug or crash, make sure that you're running the latest version of Firework and that your issue hasn't been reported already.
  - type: input
    attributes:
      label: Timings Link
      description: All timings should be a link, not a screenshot. Screenshots can get hard to read and may not include the entire context relevant to the error, so please upload a timings report instead.
      placeholder: Link to the output of /timings
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: What was the expected behavior when this bug or crash occurred?
      placeholder: Describe what was supposed to happen
    validations:
      required: true
  - type: textarea
    attributes:
      label: Observed Behavior
      description: What actually happened when this bug or crash occurred?
      placeholder: Describe the bug or crash
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug or crash? You may include build schematics, videos, or detailed instructions to help us reconstruct what happened.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Firework Version
      description: |
        Run `/version` on your server and paste the full, unmodified output here. **We don't accept screenshots!**
        "latest" is NOT a version; we require the actual output of `/version` so that we can isolate and track down the issue.
        <details>
        <summary>Example Output</summary>

        ```
        > version
        [20:47:53 INFO]: Checking version, please wait...
        [20:47:54 INFO]: Current: git-Firework-"abc123f" (MC: 1.18.2)*
        * You are running the latest version
        ```

        </details>
    validations:
      required: true
  - type: textarea
    attributes:
      label: Extra Information
      description: Please include any extra information about your bug or crash. This may include logs, error reports, or stacktraces.
      placeholder: Describe any extra information about your bug or crash
    validations:
      required: false