name: Performance Problem
description: Report performance related problems or lag spikes.
body:
  - type: markdown
    attributes:
      value: |
        Before reporting performance problems, make sure that you're running the latest version of Firework and that your problem hasn't been reported already.
        In addition, make sure that your performance problem doesn't have an obvious cause! For example, don't report lag caused by intensive server usage!
  - type: input
    attributes:
      label: Timings Link
      description: All timings should be a link, not a screenshot. Screenshots can get hard to read and may not include the entire context relevant to the error, so please upload a timings report instead.
      placeholder: Link to the output of /timings
    validations:
      required: true
  - type: textarea
    attributes:
      label: Problem Description
      description: Please fully describe your performance problem or lag spike. Include all relevant context and information, including any steps to reproduce it (if possible).
      placeholder: Describe your performance problem in detail
    validations:
      required: true
  - type: textarea
    attributes:
      label: Firework Version
      description: |
        Run `/version` on your server and paste the full, unmodified output here. **We don't accept screenshots!**
        "latest" is NOT a version; we require the actual output of `/version` so that we can isolate and track down the problem.
        <details>
        <summary>Example Output</summary>

        ```
        > version
        [20:47:53 INFO]: Checking version, please wait...
        [20:47:54 INFO]: Current: git-Firework-"abc123f" (MC: 1.18.2)*
        * You are running the latest version
        ```

        </details>
    validations:
      required: true
  - type: textarea
    attributes:
      label: Extra Information
      description: Please include any extra information about your performance problem or lag spike. This may include logs, profiling reports, or activity monitor data.
      placeholder: Describe any extra information about your performance problem
    validations:
      required: false