name: Build JAR
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Apply Patches
        run: ./gradlew applyPatches
      - name: Build Patches
        run: ./gradlew build
      - name: Generate JAR
        run: ./gradlew createReobfPaperclipJar
      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: server.jar
          path: build/libs/firework-paperclip-*.jar